server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  application:
    name: user
  data:
    mongodb:
      host: mongo.infra.svc.cluster.local
      port: 27017
      database: user
    redis:
      host: redis.infra.svc.cluster.local
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-exp-minutes: 100
  refresh-exp-days: 14

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/google/callback
  oauth:
    token-uri: https://oauth2.googleapis.com/token
    jwks-uri: https://www.googleapis.com/oauth2/v3/certs
    issuer: https://accounts.google.com

yorkie:
  jwt:
    secret: ${YORKIE_JWT_SECRET}
  webhook:
    secret: ${YORKIE_WEBHOOK_SECRET}