version: '3.8'

services:
  document-service:
    build:
      context: ./document
    container_name: pkm-document
    ports:
      - "8081:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: boardDB
      COLLECTION_NAME: posts
      PORT: 8080
    depends_on:
      - mongodb

  graph-service:
    build:
      context: ./graph
    container_name: pkm-graph
    ports:
      - "8082:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: boardDB
      COLLECTION_NAME: posts
      PORT: 8080
    depends_on:
      - mongodb

  api-gateway:
    build:
      context: ./gateway
    container_name: pkm-api-gateway
    ports:
      - "8080:8000"
    depends_on:
      - document-service
      - graph-service
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: