spring:
  application:
    name: note
  data:
    elasticsearch:
      uris: http://elasticsearch.infra.svc.cluster.local:9200
server:
  port: 8080

services:
  user:
    base-rul: ${USER_SERVICE_URL:http://user-service:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true