spring:
  application:
    name: note
  data:
    mongodb:
      host: localhost
      port: 27017
      database: note
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true