spring:
  application:
    name: note
  data:
    elasticsearch:
      uris: http://elasticsearch.infra.svc.cluster.local:9200
server:
  port: 8080

services:
  user:
    base-url: ${USER_SERVICE_URL:http://user-service:8080}
  graph:
    base-url: ${USER_SERVICE_URL:http://graph-service:8003}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true