server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: note_route
          uri: http://note-svc.rclc.svc.cluster.local:80
          predicates:
            - Path=/api/v1/notes/**
          filters:
            - StripPrefix=3
            - Logging
            - JwtAuthentication
            - name: TimeLimiter
              args:
                name: noteServiceTimeLimiter
            - name: CircuitBreaker
              args:
                name: noteServiceCircuitBreaker
                fallbackUri: forward:/fallback

        - id: graph_route
          uri: http://graph-svc.rclc.svc.cluster.local:80
          predicates:
            - Path=/api/v1/graphs/**
          filters:
            - StripPrefix=3
            - Logging
            - JwtAuthentication
            - name: TimeLimiter
              args:
                name: default
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: forward:/fallback

        - id: user_route
          uri: http://user-svc.rclc.svc.cluster.local:80
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=3
            - Logging
            - JwtAuthentication
            - name: TimeLimiter
              args:
                name: default
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: forward:/fallback

circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 5s
      recordExceptions:
        - java.io.IOException
        - java.util.concurrent.TimeoutException

    noteServiceCircuitBreaker:
      failureRateThreshold: 60
      slidingWindowSize: 20
      waitDurationInOpenState: 10s

timelimiter:
  configs:
    default:
      timeoutDuration: 2s

    noteServiceTimeLimiter:
      timeoutDuration: 3s