server:
  # 포트 번호를 환경 변수로 지정, 기본값은 8000
  port: ${GATEWAY_SERVER_PORT:8000}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  server:
    port: 8080

spring:
  cloud:
    gateway:
      server: 
        webflux:
          routes:
            - id: note_route
              uri: ${NOTE_SERVICE_URI} # http://note-svc.rclc.svc.cluster.local:80
              predicates:
                - Path=/api/v1/notes/**
              filters:
                - StripPrefix=3
                - Logging
                - JwtAuthentication
                - name: CircuitBreaker
                  args:
                    name: noteServiceCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: graph_route
              uri: ${GRAPH_SERVICE_URI}
              predicates:
                - Path=/api/v1/graphs/**
              filters:
                - StripPrefix=3
                - Logging
                - JwtAuthentication
                - name: CircuitBreaker
                  args:
                    name: default
                    fallbackUri: forward:/fallback

            - id: user_route
              uri: ${USER_SERVICE_URI:http://user-service:8080}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=3
                - Logging
                - name: JwtAuthentication
                  args:
                    publicPaths:
                      - /auth/google/callback
                - name: CircuitBreaker
                  args:
                    name: default
                    fallbackUri: forward:/fallback

circuitbreaker:
  configs:
    default:
      failureRateThreshold: ${CB_DEFAULT_FAILURE_RATE:50}
      slidingWindowType: COUNT_BASED
      slidingWindowSize: ${CB_DEFAULT_WINDOW_SIZE:10}
      minimumNumberOfCalls: ${CB_DEFAULT_MIN_CALLS:5}
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: ${CB_DEFAULT_WAIT_DURATION:5s}
      recordExceptions:
        - java.io.IOException
        - java.util.concurrent.TimeoutException

    noteServiceCircuitBreaker:
      failureRateThreshold: ${CB_NOTE_FAILURE_RATE:60}
      slidingWindowSize: ${CB_NOTE_WINDOW_SIZE:20}
      waitDurationInOpenState: ${CB_NOTE_WAIT_DURATION:10s}