info:
  contact: {}
paths:
  /connections/confirm:
    post:
      consumes:
      - application/json
      description: 제안된(pending) 또는 편집된(edited) 문서 간의 그래프 연결을 확정(confirmed) 상태로 변경합니다.
      parameters:
      - description: 연결을 확정할 Source 문서 ID 및 Target 문서 ID
        in: body
        name: request
        required: true
        schema:
          properties:
            sourceId:
              type: string
            targetId:
              type: string
            workspaceId:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 연결 확정 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "400":
          description: '잘못된 요청 형식 (예: 필수 필드 누락)'
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 연결 확정 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 그래프 연결 확정
      tags:
      - Graph Connection
  /connections/delete:
    post:
      consumes:
      - application/json
      description: 문서 간의 그래프 연결을 삭제합니다.
      parameters:
      - description: 삭제할 Source 문서 ID 및 Target 문서 ID
        in: body
        name: request
        required: true
        schema:
          properties:
            sourceId:
              type: string
            targetId:
              type: string
            workspaceId:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 연결 삭제 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 연결 삭제 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 그래프 연결 삭제
      tags:
      - Graph Connection
  /connections/edit:
    post:
      consumes:
      - application/json
      description: 사용자가 문서 간의 연결을 수동으로 편집했음을 표시하기 위해 연결 상태를 'edited'로 변경합니다.
      parameters:
      - description: 편집 상태로 설정할 Source 문서 ID 및 Target 문서 ID
        in: body
        name: request
        required: true
        schema:
          properties:
            sourceId:
              type: string
            targetId:
              type: string
            workspaceId:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 연결 편집 상태 설정 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 연결 편집 상태 설정 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 그래프 연결 편집 상태로 설정
      tags:
      - Graph Connection
  /connections/note-deleted:
    post:
      consumes:
      - application/json
      description: 외부 노트 서비스에서 노트 삭제 시 관련 그래프 연결을 모두 삭제합니다.
      parameters:
      - description: 삭제된 노트 ID
        in: body
        name: request
        required: true
        schema:
          properties:
            noteId:
              type: string
            workspaceId:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 노트 관련 그래프 연결 삭제 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 그래프 연결 삭제 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 노트 삭제 이벤트 처리
      tags:
      - Graph Connection
  /workspaces:
    get:
      description: X-User-ID 헤더에서 사용자 ID를 가져와, 해당 사용자가 소유하거나 접근 가능한 모든 워크스페이스 목록을
        반환합니다.
      parameters:
      - description: 사용자 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 워크스페이스 목록 조회 성공 및 데이터 반환
          schema:
            properties:
              data: {}
              status:
                type: string
            type: object
        "400":
          description: X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 워크스페이스 목록 조회 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 사용자가 접근 가능한 모든 워크스페이스 조회
      tags:
      - Workspace
    post:
      description: 새로운 워크스페이스를 생성합니다. 생성자는 X-User-ID 헤더에서 가져옵니다.
      parameters:
      - description: 사용자 인증을 위한 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: '워크스페이스 생성 요청 본문(type: generic, zettel, para)'
        in: body
        name: request
        required: true
        schema:
          properties:
            title:
              type: string
            type:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 워크스페이스 생성 성공 및 ID 반환
          schema:
            properties:
              status:
                type: string
              workspaceId:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식 또는 X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 워크스페이스 생성 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 생성
      tags:
      - Workspace
  /workspaces/{workspaceId}:
    delete:
      description: 워크스페이스와 해당 워크스페이스 내 모든 그래프 데이터를 삭제합니다.
      parameters:
      - description: 삭제할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: 사용자 인증을 위한 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 워크스페이스 삭제 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "400":
          description: X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 워크스페이스 삭제 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 삭제
      tags:
      - Workspace
    put:
      description: 워크스페이스 이름이나 타입을 수정합니다.
      parameters:
      - description: 수정할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: 사용자 인증을 위한 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: '워크스페이스 수정 요청 본문(type: generic, zettel, para)'
        in: body
        name: request
        required: true
        schema:
          properties:
            title:
              type: string
            type:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 워크스페이스 수정 성공 및 메시지 반환
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식 또는 X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 워크스페이스 수정 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 수정
      tags:
      - Workspace
  /workspaces/{workspaceId}/clear-pending:
    post:
      consumes:
      - application/json
      description: 워크스페이스 내 상태가 'pending'인 모든 그래프 연결을 삭제합니다.
      parameters:
      - description: 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 삭제된 pending 연결 수
          schema:
            properties:
              deletedCount:
                type: integer
            type: object
        "400":
          description: 잘못된 요청 형식
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 pending 연결 삭제 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 내 모든 pending 연결 삭제
      tags:
      - Graph Connection
  /workspaces/{workspaceId}/confirm-all:
    post:
      description: 특정 워크스페이스 내의 모든 'pending' 또는 'edit' 상태의 그래프 연결을 'confirmed' 상태로
        일괄 변경합니다.
      parameters:
      - description: 연결을 일괄 확정할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 모든 연결 확정 성공
          schema:
            properties:
              status:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 연결 확정 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 내 모든 '미완료' 연결 확정
      tags:
      - Workspace Graph
  /workspaces/{workspaceId}/graph:
    get:
      description: 특정 워크스페이스 내 모든 문서 노드와 그 연결 관계(엣지)를 조회합니다.
      parameters:
      - description: 조회할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 그래프 구조 조회 성공 및 데이터 반환
          schema:
            properties:
              data: {}
              status:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 그래프 조회 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 그래프 구조 조회
      tags:
      - Workspace Graph
  /workspaces/{workspaceId}/style:
    post:
      description: 워크스페이스의 스타일을 변경하고, 해당 스타일에 맞는 그래프 연결 작업을 비동기로 수행합니다.
      parameters:
      - description: 변경할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: 사용자 인증을 위한 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: (zettel, generic, para)
        in: body
        name: newStyle
        required: true
        schema:
          properties:
            newStyle:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 스타일 변경 성공 및 메시지 반환
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: 잘못된 요청 형식 또는 X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 스타일 변경 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 스타일 변경
      tags:
      - Workspace
  /workspaces/{workspaceId}/type:
    get:
      description: 특정 워크스페이스가 존재할 경우 해당 워크스페이스의 타입을 반환합니다.
      parameters:
      - description: 조회할 워크스페이스 ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: 사용자 ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 워크스페이스 타입 조회 성공 및 타입 반환
          schema:
            properties:
              status:
                type: string
              type:
                type: string
            type: object
        "400":
          description: X-User-ID 헤더 누락
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: 워크스페이스를 찾을 수 없거나 접근 권한 없음
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: 서버 내부 오류로 타입 조회 실패
          schema:
            properties:
              error:
                type: string
            type: object
      summary: 워크스페이스 타입 조회
      tags:
      - Workspace
swagger: "2.0"
