name: topic service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'topic/**'
  push:
    branches:
      - main
    paths:
      - 'topic/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build and Test
        working-directory: ./topic
        run: |
          go mod tidy
          go test ./...
